### ISSUE TITLE
The feelings didn't show at all. Been stuck on loading for a long time. Is it only me?

### ISSUE THREAD

**Issue by prayashm** [lauren/we-still-feel-fine#1]

**Comment by 1-800-jono** [comment]
it's happening to me too - just stuck trying to load feelings.

**Comment by iqbalrosiadi** [comment]
me as well, :(

**Comment by lauren** [comment]
Thanks @prayashm for reporting this issue and sorry for the 3.5 year delay in fixing it. There was a change to twitter's API that I had to fix. But now I've fixed it and updated a bunch of dependencies and it works again!

**Comment by prayashm** [comment]
Thank you 3000!
